### PR TITLE
Cesql v1 fixes

### LINKED ISSUE #618: Port tck tests once the CESQL spec stabilizes more
Recently there have been many changes to the CESQL spec. Once that stabilizes a bit, we should port this to this SDK and implement any fixes/changes required.

cc @pierDipi I would be happy to work on this if assigned

### PR DESCRIPTION
**Pull request by Cali0707**
Update the CESQL implementation to pass the v1 spec conformance tests.

The main change in this PR is that now the `EvaluationResult` type is used internally as well as for the final return value of the expressions, instead of using a thrower interface to collect errors over time. This allows for handling of specific exceptions that are encountered in subexpressions (for example, missing attributes). Outside of that, there are various small fixes to get the SDK to match the v1 spec.

I _tried_ to organize my work by commit, but since I wanted to get everything to pass before I did that I only sort of managed to do that. So, the commits are generally organized by what changed in them, but there may be some extra stuff in each commit. Sorry about that!

cc @pierDipi @matzew 
Fixes #618

### CODE REVIEW

File: sql/src/main/java/io/cloudevents/sql/FunctionSignature.java [hunk 1]
```diff
@@ -18,6 +18,8 @@ public interface FunctionSignature {
      */
     Type typeOfParameter(int i) throws IllegalArgumentException;
 
+    Type returnType();
```
Comment (pierDipi) [inline sql/src/main/java/io/cloudevents/sql/FunctionSignature.java:21]:
```suggestion
    /**
     * @return function return type
     */
    Type returnType();
```

Comment (pierDipi) [reply sql/src/main/java/io/cloudevents/sql/FunctionSignature.java:21]: Just for consistency with other functions

File: sql/src/main/java/io/cloudevents/sql/impl/ExceptionFactoryImpl.java [hunk 2]
```diff
@@ -0,0 +1,131 @@
...
+                EvaluationException.ErrorKind.CAST,
+                interval,
+                expression,
+                "Cannot cast " + from + " to " + to + ": " + cause.getMessage(),
+                cause
+            );
+
+            if (this.shouldFail) {
+                throw exception;
+            }
```
Comment (pierDipi) [inline sql/src/main/java/io/cloudevents/sql/impl/ExceptionFactoryImpl.java:49]: maybe "shouldThrow" is a better name ?

File: sql/src/main/java/io/cloudevents/sql/impl/ExceptionFactoryImpl.java [hunk 3]
```diff
@@ -0,0 +1,131 @@
...
+            return exception;
+        };
+    }
+
+    public EvaluationException missingAttribute(Interval interval, String expression, String key) {
+        final EvaluationException exception = new EvaluationException(
+            EvaluationException.ErrorKind.MISSING_ATTRIBUTE,
+            interval,
+            expression,
+            "Missing attribute " + key + " in the input event. Perhaps you should check with 'EXISTS " + key + "' if the input contains the provided key?",
```
Comment (pierDipi) [inline sql/src/main/java/io/cloudevents/sql/impl/ExceptionFactoryImpl.java:59]: That's an ideal error message with the suggested fix

File: sql/src/main/java/io/cloudevents/sql/impl/ExceptionFactoryImpl.java [hunk 4]
```diff
@@ -0,0 +1,131 @@
...
+            interval,
+            expression,
+            "Division by zero: " + dividend + " / 0",
+            null
+        );
+
+        if (this.shouldFail) {
+            throw exception;
+        }
+        return exception;
```
Comment (pierDipi) [inline sql/src/main/java/io/cloudevents/sql/impl/ExceptionFactoryImpl.java:113]: This could become:

```suggestion
        return mathError(interval, expression, "Division by zero: " + dividend + " / 0");
```

File: sql/src/main/java/io/cloudevents/sql/impl/runtime/EvaluationResult.java [hunk 5]
```diff
@@ -2,20 +2,79 @@
...
+        this(value, exception, null, null);
+    }
+
+    public EvaluationResult(Object value) {
+        this.value = value;
+        this.exceptions = new ArrayList<>();
+        this.latestException = null;
+    }
+
+    public EvaluationResult wrap(EvaluationResult other) {
```
Comment (pierDipi) [inline sql/src/main/java/io/cloudevents/sql/impl/runtime/EvaluationResult.java:41]: Should we call this "wrapExceptions" as I believe it would make callers code a little more explicit on what are we wrapping

Comment (pierDipi) [reply sql/src/main/java/io/cloudevents/sql/impl/runtime/EvaluationResult.java:41]: including the overloaded one

File: sql/src/test/java/io/cloudevents/sql/TCKTestSuite.java
Comment (pierDipi) [inline sql/src/test/java/io/cloudevents/sql/TCKTestSuite.java:1]: Can we fix the test suite? https://github.com/cloudevents/sdk-java/pull/603#pullrequestreview-1853465105

Comment (Cali0707) [reply sql/src/test/java/io/cloudevents/sql/TCKTestSuite.java:1]: Should be fixed now!

**Comment by pierDipi** [comment]
> Error: [ERROR] error: Error fetching URL: https://qpid.apache.org/releases/qpid-proton-j-0.33.7/api/ (java.io.FileNotFoundException: https://qpid.apache.org/releases/qpid-proton-j-0.33.7/api/package-list)

Can you completely remove that link?

**Comment by Cali0707** [comment]
Done - can you recheck this @pierDipi

**Comment by pierDipi** [comment]
Thanks @Cali0707

**Review by pierDipi — APPROVED** [review]
LGTM
