### PR TITLE
CloudEventBuilder should fail when providing an invalid extension name

### LINKED ISSUE #271: CloudEventBuilder should fail when providing an invalid extension name
The `CloudEventBuilder` should fail with the proper exception (look at `CloudEventRWException#newInvalidExtensionName`) if the user is trying to add an extension with a bad name (as specified here https://github.com/cloudevents/spec/blob/master/spec.md#attribute-naming-convention)

### PR DESCRIPTION
**Pull request by arghya88**
Signed-off-by: Arghya Sadhu <arghya88@gmail.com>

Fixes #271

### CODE REVIEW

File: core/src/main/java/io/cloudevents/core/CloudEventUtils.java [hunk 1]
```diff
@@ -102,4 +102,16 @@ public static CloudEvent toEvent(CloudEventReader reader, @Nullable CloudEventDa
         return mapper.map(data);
     }
 
+    /**
+     * Validates the extension name as defined in  CloudEvents spec
+     * @param name the extension name
+     * @return true if extension name is valid, false otherwise
+     */
+    public static boolean isValidExtensionName(String name) {
```
Comment (slinkydeveloper) [inline core/src/main/java/io/cloudevents/core/CloudEventUtils.java:110]: Don't place it in utils, just make this a private method in `BaseCloudEventBuilder`

File: core/src/main/java/io/cloudevents/core/CloudEventUtils.java [hunk 2]
```diff
@@ -102,4 +102,16 @@ public static CloudEvent toEvent(CloudEventReader reader, @Nullable CloudEventDa
         return mapper.map(data);
     }
 
+    /**
+     * Validates the extension name as defined in  CloudEvents spec
```
Comment (slinkydeveloper) [inline core/src/main/java/io/cloudevents/core/CloudEventUtils.java:106]: Can you add a link to the spec here: https://github.com/cloudevents/spec/blob/master/spec.md#attribute-naming-convention

File: core/src/test/java/io/cloudevents/core/CloudEventUtilsTest.java [hunk 3]
```diff
@@ -56,4 +56,12 @@ void mapData() {
         assertThat(i)
             .hasValue(1);
     }
+
+    @Test
+    void testIsValidExtensionName() {
```
Comment (slinkydeveloper) [inline core/src/test/java/io/cloudevents/core/CloudEventUtilsTest.java:61]: Can you test the builder more than the utils method per se?

File: core/src/main/java/io/cloudevents/core/CloudEventUtils.java [hunk 4]
```diff
@@ -102,4 +102,16 @@ public static CloudEvent toEvent(CloudEventReader reader, @Nullable CloudEventDa
...
+     * @param name the extension name
+     * @return true if extension name is valid, false otherwise
+     */
+    public static boolean isValidExtensionName(String name) {
+        if (name.matches("[a-z0-9]+") && name.length() <= 20) {
```
Comment (slinkydeveloper) [inline core/src/main/java/io/cloudevents/core/CloudEventUtils.java:111]: I wonder, can we avoid using a regexp here? Because the assertion is pretty simple, maybe we can avoid the regexp overhead by doing a char by char comparison, like for each `char c`: `(c >= 'a' && c <= 'z') || (c >= '0' && c <= '9')`

**Comment by arghya88** [comment]
@slinkydeveloper changes done.PTAL

File: core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java [hunk 5]
```diff
@@ -151,4 +160,25 @@ public CloudEvent end() {
     protected static IllegalStateException createMissingAttributeException(String attributeName) {
         return new IllegalStateException("Attribute '" + attributeName + "' cannot be null");
     }
+    /**
+     * Validates the extension name as defined in  CloudEvents spec
+     * See <a href="https://github.com/cloudevents/spec/blob/master/spec.md#attribute-naming-convention">attribute-naming-convention</a>
+     * @param name the extension name
+     * @return true if extension name is valid, false otherwise
+     */
+    public static boolean isValidExtensionName(String name) {
```
Comment (slinkydeveloper) [inline core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java:169]: Can we make it private static?

**Review by slinkydeveloper — COMMENTED** [review]
small nit and we're good to go

File: core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java (hunk 5 above)
Comment (arghya88) [reply core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java]: Done

**Comment by slinkydeveloper** [comment]
Thanks for your contribution @arghya88!
