### PR TITLE
fix: prevent NPE on deserializing JSON containing invalid `specversion` value

### LINKED ISSUE #341: Jackson CloudEventDeserializer causes NullPointerException when given JSON containing an invalid 'specversion' value
### Actual Behaviour

This code:

```
EventFormatProvider.getInstance()
    .resolveFormat(JsonFormat.CONTENT_TYPE)
    .deserialize(("{\"specversion\":\"9000.1\"}").getBytes(StandardCharsets.UTF_8));
```

gives:

```
java.lang.NullPointerException
	at com.fasterxml.jackson.databind.JsonMappingException._appendPathDesc(JsonMappingException.java:531)
	at com.fasterxml.jackson.databind.JsonMappingException.getPathReference(JsonMappingException.java:432)
	at com.fasterxml.jackson.databind.JsonMappingException._buildMessage(JsonMappingException.java:507)
	at com.fasterxml.jackson.databind.JsonMappingException.getMessage(JsonMappingException.java:490)
	at com.fasterxml.jackson.databind.JsonMappingException.toString(JsonMappingException.java:515)
	at java.lang.Throwable.<init>(Throwable.java:312)
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.RuntimeException.<init>(RuntimeException.java:96)
	at io.cloudevents.core.format.EventDeserializationException.<init>(EventDeserializationException.java:28)
	at io.cloudevents.jackson.JsonFormat.deserialize(JsonFormat.java:101)
```

### Expected Behaviour

An exception similar to this one that reports the missing mandatory `id` attribute:

```
io.cloudevents.core.format.EventDeserializationException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Missing mandatory id attribute
 at [Source: (byte[])"{"specversion":"1.0"}"; line: 1, column: 21]
	at io.cloudevents.jackson.JsonFormat.deserialize(JsonFormat.java:101)
...
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Missing mandatory id attribute
 at [Source: (byte[])"{"specversion":"1.0"}"; line: 1, column: 21]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at io.cloudevents.jackson.CloudEventDeserializer$JsonMessage.getStringNode(CloudEventDeserializer.java:163)
	at io.cloudevents.jackson.CloudEventDeserializer$JsonMessage.read(CloudEventDeserializer.java:68)
	at io.cloudevents.rw.CloudEventReader.read(CloudEventReader.java:38)
	at io.cloudevents.jackson.CloudEventDeserializer.deserialize(CloudEventDeserializer.java:195)
	at io.cloudevents.jackson.CloudEventDeserializer.deserialize(CloudEventDeserializer.java:41)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3527)
	at io.cloudevents.jackson.JsonFormat.deserialize(JsonFormat.java:99)
	... 66 more
```

### Impact

There's no guarantee that a client sending my Spring MVC REST controller `application/cloudevents+json` content will use a CloudEvents SDK to generate the request data, hence malformed content is possible. It would be helpful to easily detect deserialization errors and return a descriptive error response.

I can easily add a Spring exception handler to catch deserialisation errors such as missing mandatory attributes, _e.g._:

```
@ControllerAdvice
class CloudEventsResponseEntityExceptionHandler extends ResponseEntityExceptionHandler {
    @ExceptionHandler(EventDeserializationException.class)
    protected ResponseEntity<Object> onEventDeserializationException(EventDeserializationException e, WebRequest request) {
        return handleExceptionInternal(e, "Oops!", new HttpHeaders(), HttpStatus.BAD_REQUEST, request);
    }
}
```

However, to handle the NPE thrown when an invalid `specversion` is detected the best I can come up with is to declare `@ExceptionHandler(NullPointerException.class)` and examine the stacktrace elements looking for relevant cloudevents frames.

### Analysis

The invalid `specversion` value triggers a `CloudEventRWException` (with message _"Invalid specversion: 9000.1"_) from `SpecVersion.parse(String)` that the deserializer catches and rethrows wrapped in a `JsonMappingException`. The NPE is caused by passing a null `Reference` value in the call to `MismatchedInputException.wrapWithPath(Throwable, JsonMappingException.Reference)`.

The Jackson API doesn't specify it requires non-null `Reference` values but looking at the implementation of `JsonMappingException` it's clear they're not handled.

### Proposed Fix

I have a PR coming to rethrow using a different `MismatchedInputException` method that avoids the NPE and lets an invalid `specversion` value manifest in the same way as a missing mandatory attribute. This consistency makes exception handling in Spring MVC cleaner.

### PR DESCRIPTION
**Pull request by codebrewer**
Fixes #341

### CODE REVIEW

File: formats/json-jackson/src/test/java/io/cloudevents/jackson/CloudEventDeserializerTest.java [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+import io.cloudevents.rw.CloudEventRWException;
+import java.nio.charset.StandardCharsets;
+import org.junit.jupiter.api.Test;
+
+class CloudEventDeserializerTest {
+    @Test
+    void throwOnInvalidSpecversion() {
+        assertThatCode(() -> EventFormatProvider.getInstance().resolveFormat(JsonFormat.CONTENT_TYPE)
+            .deserialize(("{\"specversion\":\"9000.1\"}").getBytes(StandardCharsets.UTF_8)))
+            .hasMessageContaining(CloudEventRWException.newInvalidSpecVersion("9000.1").getMessage());
```
Comment (slinkydeveloper) [inline formats/json-jackson/src/test/java/io/cloudevents/jackson/CloudEventDeserializerTest.java:32]: Can you move this test in https://github.com/cloudevents/sdk-java/blob/master/formats/json-jackson/src/test/java/io/cloudevents/jackson/JsonFormatTest.java?

**Review by slinkydeveloper — COMMENTED** [review]
Thanks for contributing! Sounds good to me, just a minor comment

File: formats/json-jackson/src/test/java/io/cloudevents/jackson/CloudEventDeserializerTest.java (hunk 1 above)
Comment (codebrewer) [reply formats/json-jackson/src/test/java/io/cloudevents/jackson/CloudEventDeserializerTest.java]: Done. Would you prefer me to squash the commits into one?

**Review by slinkydeveloper — APPROVED** [review]
